cinst googlechrome
cinst firefox
cinst nodejs
cinst chocolateygui
cinst notepadplusplus
cinst sublimetext3
cinst winmerge
cinst tortoisehg
cinst sourcetree
cinst greenshot
cinst fiddler4
cinst vlc
cinst gimp
cinst skype
cinst 7zip
cinst spotify
cinst evernote
cinst mongodb
